### ISSUE TITLE
Handle changing log file names

### ISSUE THREAD

**Issue by spier** [NarrativeScience/log.io#24] opened 2012-03-14 08:30 UTC
If the name of a log file is changing frequently (e.g. daily), is there a way to still harvest such files?
Log.io doesn't seem to like symlinks.

**Comment by msmathers** [comment] 2020-04-23 12:31
This is a duplicate of #211, closing

**Closed by msmathers** 2020-04-23 12:31 UTC

**Comment by msmathers** [comment] 2020-04-23 21:14
Support for globs and new file detection have been added in v0.4.14 https://github.com/NarrativeScience/log.io/releases/tag/v0.4.14
